# general setting
batch_size: 16
input_size: 32
gt_size: 64
ch_size: 3
scale: 2
sub_name: 'esrgan_ea_X2_bicubic'
bootstrap_model : 'esrgan'


# generator setting
network_G:
    nf: 64
    nb: 23
# discriminator setting
network_D:
    nf: 64

# dataset setting
train_dataset:
    path: './data/DIV2K_train_LR_bicubic_X2_sub.tfrecord'
    num_samples: 32208
    using_bin: False
    using_flip: True
    using_rot: True
test_dataset:
    HR_path: './data/DIV2K/DIV2K_valid_HR'
    LR_bicubic_path: './data/DIV2K/DIV2K_valid_LR_bicubic/X2'

# training setting
niter: 100000

lr_G: !!float 5e-4
lr_D: !!float 5e-4
lr_steps: [50000, 100000, 200000, 300000]
lr_rate: 0.5

adam_beta1_G: 0.9
adam_beta2_G: 0.99
adam_beta1_D: 0.9
adam_beta2_D: 0.99

w_pixel: !!float 1e-2
pixel_criterion: l1

w_feature: 1.0
feature_criterion: l1

w_edge: 2.0
edge_criterion: l1

w_gan: !!float 5e-3
gan_type: ragan  # gan | ragan

save_steps: 5000
